'use client';
import { useState } from 'react';
import styles from './WeeklyDigest.module.css';

interface Props {
  boardId: string;
  boardTitle: string;
  onClose: () => void;
}

export default function WeeklyDigest({ boardId, boardTitle, onClose }: Props) {
  const [loading, setLoading] = useState(false);
  const [digest, setDigest] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/ai', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'weekly_digest', payload: { boardId } }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setDigest(data.digest);
    } catch (e: any) {
      setError(e.message || 'Failed to generate digest');
    } finally {
      setLoading(false);
    }
  }

  // Simple markdown to HTML (bold, italics, headers, line breaks)
  function renderMarkdown(text: string) {
    return text
      .replace(/^## (.+)$/gm, '<h3 class="digestH3">$1</h3>')
      .replace(/^### (.+)$/gm, '<h4 class="digestH4">$1</h4>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>[^<]*<\/li>\n?)+/g, '<ul>$&</ul>')
      .replace(/\n/g, '<br/>');
  }


  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className={`modal-box ${styles.modal}`} onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className={styles.header}>
          <div className={styles.headerLeft}>
            <div className={styles.icon}>⚡</div>
            <div>
              <h2 className={styles.title}>AI Weekly Digest</h2>
              <p className={styles.subtitle}>{boardTitle} · Last 7 days</p>
            </div>
          </div>
          <button className="btn btn-ghost btn-icon" onClick={onClose} aria-label="Close">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className={styles.body}>
          {!digest && !loading && !error && (
            <div className={styles.cta}>
              <div className={styles.ctaIcon}>🤖</div>
              <p className={styles.ctaText}>
                Generate a smart summary of this week's board activity, including key milestones, team contributions, and suggested next steps.
              </p>
              <button className="btn btn-primary" onClick={generate} id="digest-generate-btn">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>
                </svg>
                Generate Digest
              </button>
            </div>
          )}

          {loading && (
            <div className={styles.loading}>
              <div className={styles.spinner} />
              <p>Analyzing board activity with Llama AI…</p>
              <span className={styles.loadingNote}>Usually takes 3-5 seconds</span>
            </div>
          )}

          {error && (
            <div className={styles.error}>
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/>
              </svg>
              <p>{error}</p>
              <button className="btn btn-ghost btn-sm" onClick={generate}>Retry</button>
            </div>
          )}

          {digest && !loading && (
            <div className={styles.digest}>
              <div
                className={styles.digestContent}
                dangerouslySetInnerHTML={{ __html: renderMarkdown(digest) }}
              />
              <div className={styles.digestFooter}>
                <span className={styles.model}>Generated by Llama-3.1-8B via Groq</span>
                <button className="btn btn-ghost btn-sm" onClick={generate}>
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-.49-5.99"/>
                  </svg>
                  Regenerate
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
